gsislogin.GSISID:
 type: config_object
 label: 'Gsis consumer id'
 mapping:
   title:
     type: text
     label: 'Gsis id'

gsislogin.GSISSECRET:
 type: config_object
 label: 'Gsis consumer secret'
 mapping:
   title:
     type: text
     label: 'Gsis secret'

gsislogin.GSISTEST:
 type: config_object
 label: 'Gsis test server'
 mapping:
   title:
     type: text
     label: 'Gsis test enabled'
